### ISSUE TITLE
无法添加控制点

### ISSUE THREAD

**Issue by MrHeer** [venshine/BezierMaker#2]
我将您的项目在Android Studio上构建想学习一下，不过发现我不能添加控制点，不知道为什么

**Comment by chenshandong** [comment]
me too! I can not add more points.

**Comment by Einsteinford** [comment]
源码改一下嘛，就onMeasure的getWidth()那2个地方改成getMeasuredWidth()

**Comment by MrHeer** [comment]
@Einsteinford 谢谢啦，现在都没时间去学习，有机会再去看看
